apiVersion: v1
kind: Service
metadata:
  name: pipeline-analyzer-service
spec:
  type: LoadBalancer
  selector:
    app: pipeline-analyzer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
